# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "915084733740dff09b601d70b773dac0"
name = "custom-wishlist"
application_url = "https://custom-wishlist-zufv.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://custom-wishlist-zufv.onrender.com/api/auth" ]

[app_proxy]
url = "https://custom-wishlist-zufv.onrender.com/apps/wishlist"
subpath = "wishlist"
prefix = "apps"

[customer.metafields.app.wishlist]
type = "list.single_line_text_field"
name = "Wishlist"
description = "Product handles saved by the customer"

  [customer.metafields.app.wishlist.access]
  admin = "merchant_read_write"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
