api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Customer wishlist"
handle = "customer-account-wishlist"

uid = "2842f224-d987-cfea-47c3-182398c28d103c711e42"

[[extensions.targeting]]
module = "./src/CustomerAccountWishlist.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true